name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Update APT sources
      run: sudo apt update
    
    - name: Install dependencies
      run: sudo apt install git bc bison flex libssl-dev make crossbuild-essential-arm64
      
    - name: Build Linux
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
            mkdir out
            make O=out/ ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- vendor/bengal-perf_defconfig
            make -j$(nproc) O=out/ \
                      ARCH=arm64 \
                      CROSS_COMPILE=aarch64-linux-gnu-
      
    - uses: actions/upload-artifact@v3
      with:
       name: Upload built directory
       path: ${{ github.workspace }}/out/arch/arm64/boot/
